"""update stack table

Revision ID: 5a966b9a8f04
Revises: aef6392b413d
Create Date: 2024-02-12 16:05:45.233789

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a966b9a8f04"
down_revision: Union[str, None] = "aef6392b413d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stack", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stack",
        sa.Column(
            "type",
            postgresql.ENUM("language", "framework", "software", name="stack_type"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
