"""add all tables

Revision ID: 88a15984c1d7
Revises: 
Create Date: 2024-01-27 20:58:41.356850

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88a15984c1d7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "education",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("degree", sa.String(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=False),
        sa.Column("cgpa", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "languages",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "profile",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("tel", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("github", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("first_name"),
    )
    op.create_table(
        "projects",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("year", sa.DateTime(), nullable=False),
        sa.Column("stack", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("tasks", sa.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("title"),
    )
    op.create_table(
        "stack",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "_type",
            sa.Enum("language", "framework", "software", name="stack_type"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stack")
    op.drop_table("projects")
    op.drop_table("profile")
    op.drop_table("languages")
    op.drop_table("education")
    # ### end Alembic commands ###
