"""remove tel from profile model

Revision ID: 98143ad5a769
Revises: 88a15984c1d7
Create Date: 2024-02-10 20:17:30.670011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98143ad5a769'
down_revision: Union[str, None] = '88a15984c1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'tel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('tel', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
