"""update column name on stack table

Revision ID: aef6392b413d
Revises: 98143ad5a769
Create Date: 2024-02-12 16:02:48.251814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aef6392b413d'
down_revision: Union[str, None] = '98143ad5a769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education', 'cgpa')
    op.add_column('stack', sa.Column('type', sa.Enum('language', 'framework', 'software', name='stack_type'), nullable=True))
    op.drop_column('stack', '_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stack', sa.Column('_type', postgresql.ENUM('language', 'framework', 'software', name='stack_type'), autoincrement=False, nullable=True))
    op.drop_column('stack', 'type')
    op.add_column('education', sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
